# -*- python -*-
Import("env")

env.Program(["BuildExcept.cc"], LIBS=env.libs["boost"] + ["utils"] + ["daf_base"] + ["pex_logging"] + ["pex_exceptions"])

env.CheckSwig("python", ilang="c++")
env.Append(SWIGFLAGS=" -Ipython")
exceptionTests = env.LoadableModuleIncomplete("_exceptionTests", "exceptionTests.i", LIBS=env.libs["utils"] + ["daf_base"] + ["pex_logging"] + ["pex_exceptions"])

#
# Tests
#
import lsst.tests
import os

tests = lsst.tests.Control(env, ignoreList=['exceptionTests.py'], verbose=True)

tests.run("BuildExcept.cc")

for target in tests.run("*.py"):
    env.Depends(target, exceptionTests)
