# -*- python -*-
Import("env")

env.Program("Exception_1.cc", LIBS=env.getlibs("pex_exceptions") + env.gettestlibs("boost"))

failerLib = env.LoadableModuleIncomplete("failer", Split("failerLib.cc Failer.cc"),
                                         LIBS=env.getpylibs("pex_exceptions bputils"))

#
# Tests
#
import lsst.scons.tests
import os

tests = lsst.scons.tests.Control(env, verbose=True)

tests.run("Exception_1.cc")
for target in tests.run("Exception_*.py"):
    env.Depends(target, failerLib)
    env.Depends(target, "../python/lsst/pex/exceptions/exceptionsLib.so")
