# -*- python -*-
Import('env')
import os

env.SharedLibrary('pex_exceptions',
                         map(lambda str: "../src/" + str,
                            ["Exception.cc"
                            ]), LIBS=env.getlibs("boost utils daf_base"))
