# -*- python -*-
Import('env')

env.Program("exceptions", ["exceptions.cc"], LIBS=env.libs["boost"] + ["utils"] + ["daf_base"] + ["pex_exceptions"])

#
# Tests
#
import lsst.tests
tests = lsst.tests.Control(env, verbose=True)

if tests.runExamples:
    tests.run("*.cc")
    tests.run("*.py")
