# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils")
env.LoadableModuleIncomplete("_exceptionsLib", Split("exceptionsLib.i"), LIBS=env.libs["boost"] + ["daf_base"] + ["pex_exceptions"])

